In [2]:
import torch 
import numpy as np

In [12]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)


In [13]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [17]:
n = np.ones(5)
t = torch.from_numpy(n)

t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [18]:
np.add(n, 1, out=n)
print(n)
print(t)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
# mini exercise

x = torch.randn(32, 200)
x.mean(dim=1, keepdim=True)

torch.Size([32, 1])

In [29]:
rez = (x - x.mean(dim=1, keepdim=True)) / x.std(dim=1, keepdim=True)

In [32]:
rez.mean(dim=1)

tensor([-1.0729e-08,  7.1526e-09,  5.9605e-09,  2.3842e-09,  1.1921e-09,
         4.7684e-09,  1.9073e-08, -2.6226e-08,  1.1921e-08,  2.2650e-08,
         2.3842e-09, -1.4305e-08,  9.5367e-09,  2.6226e-08,  4.7684e-09,
        -2.3842e-09, -2.0862e-08,  9.5367e-09, -7.1526e-09,  0.0000e+00,
         0.0000e+00, -1.1921e-09,  9.5367e-09,  5.3644e-09,  4.7684e-09,
        -1.0133e-08,  8.3447e-09,  0.0000e+00,  4.7684e-09,  7.1526e-09,
        -9.5367e-09,  1.1921e-09])

In [33]:
rez.std(dim=1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000])

In [34]:
if torch.accelerator.is_available():
    rez = rez.to(torch.accelerator.current_accelerator())



In [35]:
rez[0]

tensor([ 0.0313, -0.5892,  0.5392, -1.9325,  2.0597,  0.4654, -0.1604, -1.3123,
        -1.6005, -1.5021, -0.1282, -0.6023,  0.1006, -2.0294,  1.9401, -1.6247,
         0.5629, -0.2168,  1.0395,  1.8556,  0.6795, -0.5998,  0.1167,  0.6543,
         0.5056,  1.0921, -1.6029, -0.2222, -0.5183, -0.9309,  0.1055,  1.2817,
        -0.3371,  0.6342, -0.2874, -0.8130, -1.1505,  2.6751,  1.6541, -0.1889,
         0.7987,  0.4590, -0.7436, -0.2674, -2.8114,  0.6575,  1.4144, -0.1545,
        -0.1659, -0.6400,  1.2839, -0.7099, -1.0063, -1.0377,  1.1494, -0.5457,
         1.0607,  0.1872,  1.4192,  0.5314, -0.8451, -0.8355,  0.0683, -0.6143,
        -1.5915,  0.9260,  0.7530,  0.7188,  1.4505,  0.1277,  0.4247, -0.8002,
        -1.6572,  0.8886,  0.2205,  0.2946,  0.0725,  0.2093, -0.0185,  0.0722,
        -0.3092, -1.5901,  1.3880, -0.9141, -0.0203, -0.7261, -0.1721, -1.2253,
        -1.0138, -1.2506,  0.1987,  1.5731, -0.3592,  0.3509, -0.5136,  1.4675,
         0.4657, -0.4771, -0.7445,  0.96

In [36]:
rez[:,0]


tensor([ 0.0313,  0.1506, -1.8942,  0.8462, -0.7120,  1.7821,  0.9592,  1.9180,
         1.6010,  0.2443, -1.3346, -0.3241, -0.3829, -0.0940, -0.0493, -1.7321,
        -0.2040, -0.8769, -1.5860,  0.4917, -1.3643,  1.1643,  0.4635, -0.9839,
        -0.0755,  0.0157, -0.7151,  1.1809, -0.0175,  1.1497, -1.1288, -0.9510],
       device='mps:0')

In [39]:
(rez @ rez.T).shape

torch.Size([32, 32])